// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: get_users.proto

package myPkgName

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetUsersServiceClient is the client API for GetUsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetUsersServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserWithInject(ctx context.Context, in *GetUserWithInjectRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type getUsersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetUsersServiceClient(cc grpc.ClientConnInterface) GetUsersServiceClient {
	return &getUsersServiceClient{cc}
}

func (c *getUsersServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/get_users.GetUsersService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getUsersServiceClient) GetUserWithInject(ctx context.Context, in *GetUserWithInjectRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/get_users.GetUsersService/GetUserWithInject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUsersServiceServer is the server API for GetUsersService service.
// All implementations must embed UnimplementedGetUsersServiceServer
// for forward compatibility
type GetUsersServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUserWithInject(context.Context, *GetUserWithInjectRequest) (*GetUserResponse, error)
	mustEmbedUnimplementedGetUsersServiceServer()
}

// UnimplementedGetUsersServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGetUsersServiceServer struct {
}

func (UnimplementedGetUsersServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedGetUsersServiceServer) GetUserWithInject(context.Context, *GetUserWithInjectRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserWithInject not implemented")
}
func (UnimplementedGetUsersServiceServer) mustEmbedUnimplementedGetUsersServiceServer() {}

// UnsafeGetUsersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetUsersServiceServer will
// result in compilation errors.
type UnsafeGetUsersServiceServer interface {
	mustEmbedUnimplementedGetUsersServiceServer()
}

func RegisterGetUsersServiceServer(s grpc.ServiceRegistrar, srv GetUsersServiceServer) {
	s.RegisterService(&GetUsersService_ServiceDesc, srv)
}

func _GetUsersService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUsersServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/get_users.GetUsersService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUsersServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GetUsersService_GetUserWithInject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserWithInjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUsersServiceServer).GetUserWithInject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/get_users.GetUsersService/GetUserWithInject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUsersServiceServer).GetUserWithInject(ctx, req.(*GetUserWithInjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetUsersService_ServiceDesc is the grpc.ServiceDesc for GetUsersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetUsersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "get_users.GetUsersService",
	HandlerType: (*GetUsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _GetUsersService_GetUser_Handler,
		},
		{
			MethodName: "GetUserWithInject",
			Handler:    _GetUsersService_GetUserWithInject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "get_users.proto",
}
